export const ADD_YCMH_PHONGBAN = 'ADD_YCMH_PHONGBAN';
export const ADD_YCMH_DOANHNGHIEP = 'ADD_YCMH_DOANHNGHIEP';
export const ADD_DONMUAHANG = 'ADD_DONMUAHANG';
export const EDIT_DATAODONMUAHANG = 'ADD_DATAODONMUAHANG';
// export const DELETE_FROM_CART = 'DELETE_FROM_CART';
// export const UPDATE_FROM_CART = 'UPDATE_FROM_CART';
// export const CLEAR_CART = 'CLEAR_CART';
